name: test-env
channels:
  - deepmodeling
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - scipy
  - h5py
  - paramiko
  - ruamel.yaml=0.17.21
  - pytorch
  - mpich
  - abacus=3.9.0.2
  - pytest
  - psutil
  # - pyscf
  # - dpdispatcher
  - pip
  - pip:
      - -e .