name: Integration Test and Unit Test

on:
  pull_request:
    branches: 
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: PyTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github
        uses: actions/checkout@v4
      
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.12
          channels: deepmodeling,conda-forge,defaults
          channel-priority: true
          activate-environment: test-env
          environment-file: environment.yml
          use-mamba: true

      # - name: Install pip-only dependencies
      #   shell: bash -l {0}
      #   run: |
      #     pip install -e .

      - name: Unit Test with PyTest
        run: |
          conda activate test-env
          pytest tests/unittests/ -s

      - name: Integration Test withs PyTest
        env:
          ROOT_DIR: ${{ github.workspace }}
        run: |
          pytest tests/integral/

      # - name: Archive Pytest test report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: SuperTest-test-report
      #     path: report
            
      # - name: Upload Pytest report to GitHub
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Pytest-test-report
      #     path: report